# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f8edc4c52d9b064039fe4745f2176c6589411569c85dda9777c5bc2b63f285a9b08dc5c45112358d79e047920168870504a4ea4ff61c2ef4f065238090f49f5

test:
  secret_key_base: b989152e2706a34560cbbf7b0e33a7353774c8cf3d5f778def3eb353ac1cf538fcabe3c96b1c53d832c1f61802ada31c46187ff6b19614bd49807f96e4c8cec0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
